name: CI/CD Pipeline

on:
  push:
    branches:
      - main   # Run workflow whenever code is pushed to main branch

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: docker build -t my-api-app .

    - name: Test Docker image
      run: docker run my-api-app python app.py
